language: python
python:
  - "3.5"
before_install:
  - wget -q -N https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz --directory /home/travis/miniconda3/bin
# command to install dependencies
install:
  - pip install -r requirements.txt
  - travis_retry bundle install
  - bundle install
before_script:
  - wget http://ftp.mozilla.org/pub/firefox/releases/52.0/linux-x86_64/en-US/firefox-52.0.tar.bz2
  - tar xvjf firefox-52.0.tar.bz2
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver  
  - export PATH=$PWD/firefox:$PATH:$PWD/geckodriver
# command to run tests
script:
  - py.test # or py.test for Python versions 3.5 and below
