language: python
python:
  - "3.5"
before_install:
  - curl -L -o /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER_VERSION/geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz
  - mkdir $HOME/geckodriver && tar xvf /tmp/geckodriver.tar.gz -C $HOME/geckodriver
  - export PATH=$HOME/geckodriver:$PATH
  - geckodriver --version
# command to install dependencies
install:
  - pip install -r requirements.txt
  - travis_retry bundle install
  - bundle install
# command to run tests
script:
  - py.test # or py.test for Python versions 3.5 and below
